extends:
- "airbnb"

rules:
  jsx-a11y/href-no-hash: off
  react/jsx-filename-extension: off
  jsx-a11y/no-noninteractive-element-interactions: off
  import/no-dynamic-require: off
  global-require: off
  jsx-a11y/alt-text: off
  react/forbid-prop-types: off
  jsx-a11y/no-static-element-interactions: off
# "jsx-a11y/anchor-is-valid": ["warn", { "aspects": ["invalidHref"] }]